.TH GBGOFFICE 1 "February 2005"
.SH NAME
gbgoffice \- GTK BG Office assistant
.SH SYNOPSIS
.B gbgoffice [OPTIONS]...
.SH DESCRIPTION
gbgoffice - GTK BG Office assistant
.SH OPTIONS
.IP "-d, --dump-data-dir"
Dumps direcotry where shared files are instaled.
.IP "-l, --language=[bg/en]"
Sets language to Bulgarian or English.
.IP "-h, --help"
Display help message.
.IP "-v, --version"
Display the version of the program.
.SH FILES
.I ~/.gbgoffice
.RS
Per user configuration file. 
.SH ENVIRONMENT
.IP LANG
Specify language which will be used (Bulgarian or English)
.SH BUGS
Trayicon may not work with all window managers.
.SH LICENSE
This  program  is distributed under the terms of the GNU General Public License as published by the Free Software Foundation. See COPYING or COPYING.BULGARIAN for details.
.SH "SEE ALSO"
.BR kbgoffice (1),
.BR cbgoffice (1)

official webpage - http://gbgoffice.info
.SH AUTHORS
Miroslav Yordanov <mironcho at linux-bg dot org>
