# Dictionaries from the BG Office full-pack (http://bgoffice.sourceforge.net).
# Installed into $(pkgdatadir), i.e. $(datadir)/bgoffice (/usr/share/bgoffice
# with --prefix=/usr), the directory gbgoffice searches by default.

pkgdata_DATA = \
	bg-en.dat \
	bg-en.test \
	bg-en_dual.dict \
	bg_en_dual.xpm \
	computer_terms.dat \
	computer_terms.dict \
	computer_terms.xpm \
	dialect.dat \
	dialect.dict \
	dialect.xpm \
	en-bg.dat \
	en-bg.test \
	polytechnical.dat \
	polytechnical.dict \
	polytechnical.xpm \
	thesaurus.dat \
	thesaurus.dict \
	thesaurus.test \
	thesaurus.xpm
